name: Deploy Frontend to Heroku

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy client/ to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/my-frontend-app.git
          git subtree push --prefix client heroku main
